### DISCUSSION TITLE
Custom load power settings for PowerStream local/private API?

### DISCUSSION THREAD

**Discussion by Jamie-Jameson** [tolwi/hassio-ecoflow-cloud#456] [Ideas]
Hi there,

I finally managed to configure the public API with ecoflow_cloud. A BIG BIG thank you for this great integration. This is pretty much exactly what I was looking for. I use this for monitoring and - more importantly - to configure the current "household demand" at the inverter, which I read from a Tasmota head via MQTT. For this, I setup a simple automation triggered by changes of the Tasmota current power sensor.

I'd like to know if it would be possible to have the "Custom load power settings" (number.powerstream_2749_custom_load_power_settings) also available in the local / private API? I'd love to use the local API to avoid the cloud communication overhead and round-trip. However, without the possibility to configure this entity there is no sense for me to even test the local API mode.

If this is not possible, I'd still be interested why that it.

Cheers,
Jamie

**Comment by HansMeulenbroek** [comment]
Hi,

I'm quite new to HA have it connected to EcoFlow Cloud Public app and am trying to find an easy wat to implement "Null-Einspeisung": minimize power to the grid. I just have tested this automation:
![Scherm­afbeelding 2025-06-03 om 20 03 58](https://github.com/user-attachments/assets/b5277a7e-c7be-4dfd-ac04-ebd9d697e745)
I'm only able to put a value in (in steps of 100) but would like to use a variable.... this function is quite fast and would love to see if anyone has ideas how to implement this. I have tried to put a variable {{ (states('input_number.load_setpoint') | float) }} with File editor in the automations.yaml but that didn't work.

Mit freundliche Grusse, Kind regards, Hans

**Comment by ByteWolfGang** [comment]
Sorry, I read you need a private API solution....this one would be for public API:

Maybe this automation YAML will help you with Home Assistant:
```

description: "Set Powerstream Custom Load to current demand"
mode: single
trigger:
  - platform: time_pattern
    seconds: "/30"
condition: []
action:
  - service: number.set_value
    target:
      entity_id: number.custom_load_power_settings
    data:
      value: >
        {%- set consumption = states('sensor.CurrentTotalPowerConsumption') | float(0) -%}
        {%- set feedin      = states('sensor.CurrentInverterOutputWatts') | float(0) -%}
        {%- set raw = consumption + feedin -%}
        {{ [0, [raw, 800] | min] | max | round(0) | int }}
```


CurrentTotalPowerConsumption is the Sensor providing your demand/consumption.
CurrentInverterOutputWatt is the sensor of the Powerstream Inverter output watts.
custom_load_power_settings is the datapoint to be set from this Integration (public Ecoflow API)

Now, PowerStream will only invert the energy you need
