### ISSUE TITLE
Remove device_class for number entities

### ISSUE THREAD

**Issue by chertvl** [tolwi/hassio-ecoflow-cloud#101]
Hello ;)

I dont know why and what for, but number.* entities of integration has a device_class'es:

```
number.ecoflow_ac_charging_power
  device_class: power
number.ecoflow_max_charge_level:
  device_class: battery
number.ecoflow_min_discharge_level:
  device_class: battery
number.ecoflow_backup_reserve_level:
  device_class: battery
```

This leads to some bugs, for example,  the first found object with the ```device_class: battery``` will be displayed as **device battery with icon** in the list of HA devices. If I have a 50% on "Backup Reserve" entity (slider), then  I will see 50% in the HA devices list (instead of an ecoflow real (Main) battery percentage).

I suggest not using device class for number.* objects.

P.S.:
Temporarily solved with customize_glob:
```
"number.ecoflow_*":
  device_class: None
```
