### ISSUE TITLE
[New Device] Smart Home Panel

### ISSUE THREAD

**Issue by Ne0-Hack3r** [tolwi/hassio-ecoflow-cloud#140]
I there any interest in adding the Smart Home Panel to this integration? I have done so using a YAML package and Mosquito broker on Home Assistant but never got round to creating a proper integration. I would be willing to contribute information, testing, etc. if that is something others would like to see added and @tolwi is interested in doing.

**Comment by dafmeuk** [comment]
Absolutely! An integration would be hugely valuable to me.

**Comment by Thomptronics** [comment]
+1

**Comment by bluefire100** [comment]
Is SHP already implemented?

**Comment by Ne0-Hack3r** [comment]
@tolwi 

Any interest in collaborating to add SHP support to your integration?

**Comment by dafmeuk** [comment]
@towli … I’d just like to encourage you to take up the offer from @Ne0-Hack3r to collaborate on adding Smart Home Panel support to hassio-ecoflow-cloud

I’ve been able to do some truly useful automations with my Delta Pro’s, but the main thing holding back the potential of my automations is not being able to control when the Smart Home Panel ports are set to charge, and switching circuits to battery or mains. The SHP side of my automations can only ever be time based rules with Ecoflow’s native automations, which is really restrictive. I’m still using the original hassio-ecoflow integration, but would switch everything over to hassio-ecoflow-cloud in an instant it it would get me SHP support.

**Comment by Ne0-Hack3r** [comment]
@dafmeuk 

There is a way to do this by building your own YAML package (or using mine as a base). But it is fairly involved compared to just loading a HACS integration. Given that I already have the key/value structure for all the SHP sensors and settings I'd just need some help understanding how to incorporate that into the python integration (or I can simply provide what I already have and let the author add it to this integration), I'd be happy to test and debug in that case as well.

**Comment by tolwi** [comment]
@Ne0-Hack3r attach your yaml and I'll try to provide you with a draft version for testing (I don't have SHP so I can not verify anything)

**Comment by Ne0-Hack3r** [comment]
@tolwi 

I'm happy to share whatever you need and have invited you to my private repo.

The specific YAML package file is here:
https://github.com/Ne0-Hack3r/ef-mqtt-hacks-ha/blob/main/shp/shp_integration.yaml

**Comment by Ne0-Hack3r** [comment]
@tolwi

There is a bunch more in that YAML that is needed to provide access to all the relevant sensors and settings and the package has evolved quite a bit around my own personal usage. Obviously your integration should just expose all relevant entities and let those that want to build something more elaborate create their own helpers, automations, etc.

**Comment by Ne0-Hack3r** [comment]
@dafmeuk 

I might caution against trying to automate everything for the SHP within home assistant. While it can be done there are caveats to consider:

For example: if you create no automations other than setting up the built in outage automation and then automate daily usage/cycling by setting individual circuits to "use power station" you then also have to handle the fallback to grid (prior to discharge limit) or when the battery hits that limit your circuits will turn OFF. "use power station" means "only ever use power station" (never use grid) and vice versa. So you may want to go the route of creating an automation that runs 24x7x365 and then enabling or disabling it using an HA automation. Perhaps in adding SHP to this HACS integration we can expose an on/off switch for each active automation (or some such). Just trying to explain that SHP integration gets a bit complicated when it comes to automations and the internal handling of when/how things fall back to grid, etc.

**Comment by tolwi** [comment]
> The specific YAML package file is here: https://github.com/Ne0-Hack3r/ef-mqtt-hacks-ha/blob/main/shp/shp_integration.yaml

Can you add a few raw json messages from mqtt to you repo, please.

**Comment by dafmeuk** [comment]
> @dafmeuk
> 
> I might caution against trying to automate everything for the SHP within home assistant. While it can be done there are caveats to consider:
> 
> For example: if you create no automations other than setting up the built in outage automation and then automate daily usage/cycling by setting individual circuits to "use power station" you then also have to handle the fallback to grid (prior to discharge limit) or when the battery hits that limit your circuits will turn OFF. "use power station" means "only ever use power station" (never use grid) and vice versa. So you may want to go the route of creating an automation that runs 24x7x365 and then enabling or disabling it using an HA automation. Perhaps in adding SHP to this HACS integration we can expose an on/off switch for each active automation (or some such). Just trying to explain that SHP integration gets a bit complicated when it comes to automations and the internal handling of when/how things fall back to grid, etc.

Thanks for the advice. To be honest, creating a few Ecoflow automations that each run 24/7 and just activating/deactivating the one I want using HA would achieve what I need perfectly.

My situation is that I have both grid-tied solar (I.e. with an inverter supplying AC to the house) as well as some DC solar going directly into the Delta Pros. The AC coupled solar can export to the grid, and so I monitor that with a Shelly CT and use HA to dynamically raise or lower the Delta Pro charging level to match the grid export/import and make sure I’m charging just enough to balance the generation and self-consume all the grid-tied solar. This works well when I’m generating more than I’m using, but I also want the batteries to power the SHP circuits so that I’m also not drawing from the grid when my usage is higher than the generation. Unfortunately the Smart Home Panel is only ever using a Delta Pro to power the SHP circuits or to charge it, one Delta Pro can’t do both things at the same time.  I get round this because I have two Delta Pro’s, so one can be soaking up excess solar while the other one is supplying the SHP circuits, and so I it keeps the house balanced, neither exporting nor importing. However, I also need to alternate the two Delta Pro’s through the day so I don’t end up with one full and one empty, and I do this through an EcoFlow automation on the SHP that periodically swaps Port 1 or Port 2 to be charging. The only way I can do this at the moment is to just have alternating time windows for each port in the Ecoflow rules and just hope that each battery get roughly the same amount of opportunity to charge versus discharge. I also realise this is not efficient to be both charging one Delta Pro and dischaging the other at the same time when the AC could have just been used directly.

Hence what I really need to be able to do is automate when the SHP is charging on Port 1 / Port 2 or both/neither, depending on whether I am generating more than I’m using or less and depending on which battery is lowest.

I also am on an electricity tariff where my overnight cheap rate sometimes starts earlier in the evening, not always a fixed time. My energy provider has a HA sensor that I can use to  trigger an automation when this cheap rate kicks in, but I would like to automatically switch from all circuits on battery to both batteries charging when the cheap rate starts, but at the moment I can only achieve this with a fixed time automation in the SHP EcoFlow rules, not from HA, so that’s a second reason why a SHP integration would be really useful.

**Comment by Ne0-Hack3r** [comment]
> > The specific YAML package file is here: https://github.com/Ne0-Hack3r/ef-mqtt-hacks-ha/blob/main/shp/shp_integration.yaml
> 
> Can you add a few raw json messages from mqtt to you repo, please.

@tolwi 

https://github.com/Ne0-Hack3r/ef-mqtt-hacks-ha/blob/main/shp/shp_raw.json

In addition to those samples there is one that rotates through on a less frequent basis unless a change is made to the charge/discharge limits. In my YAML package I use an automation that is triggered by this params.id to repost it to a separate topic on my local MQTT with a retained flag. You may have a better way to handle that within the integration. This was a bit of a work around to avoid long periods of the sensor sitting in "unknown" status when things got reloaded. a kluge at best.

```
{"params":{"forceChargeHigh":100,"cmdSet":11,"discLower":5,"id":30},"version":"1.0","cmdId":0,"cmdFunc":0,"id":1585896662957696715,"addr":0,"timestamp":1699358670545}
```

As with all the other devices a payload can be posted to ../get requesting "latestQuotas" which will return a large payload on ../get_reply containing the current state of all sensors. This is great for pre-populating sensor data but I did not think polling constantly for that was a particularly elegant way to handle it within a YAML package (basically using an automation to post the request every X seconds). Probably not too 'friendly' to the cloud mqtt server and possibly a way to get the account flagged as the app only posts that once when entering the screen for a given device.

**Comment by Ne0-Hack3r** [comment]
@dafmeuk

Sounds like you are running 2 DPs on SHP in single phase as am I. I use an automation along with a smart plug attached to a 1400W space heater plugged into a circuit supplied by SHP to "induce" parallel mode which has the effect of using both DPs for 1 minute after which the DP at lower SOC disengages... 

```
alias: SHP - Load Balance
description: SHP - Load Balance
trigger:
  - platform: numeric_state
    entity_id: sensor.dp_all_soc_delta
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 10
condition:
  - condition: numeric_state
    entity_id: sensor.shp_all_pro_output
    above: 300
  - condition: state
    entity_id: binary_sensor.shp_pro1_ac_charging
    state: "off"
  - condition: state
    entity_id: binary_sensor.shp_pro2_ac_charging
    state: "off"
  - condition: or
    alias: Only one DP discharging
    conditions:
      - condition: and
        alias: Only DP1
        conditions:
          - condition: state
            entity_id: switch.dp1_ac_output
            state: "on"
          - condition: state
            entity_id: switch.dp2_ac_output
            state: "off"
      - condition: and
        alias: Only DP2
        conditions:
          - condition: state
            entity_id: switch.dp1_ac_output
            state: "off"
          - condition: state
            entity_id: switch.dp2_ac_output
            state: "on"
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.basement_plug
  - wait_template: "{{ int(states('sensor.shp_all_pro_output')) > 1900 }}"
    alias: Wait up to 30 seconds for AC output >1900W
    timeout: "30"
    continue_on_timeout: true
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.basement_plug
  - delay:
      hours: 0
      minutes: 9
      seconds: 0
      milliseconds: 0
mode: single
```

This uses a combination of my YAML package for SHP, the hassio (local) integration for DP, the integration for my smart plug, and a custom sensor I built called 'dp_all_soc_delta' that tracks the SOC differential between the two DPs...

```
- platform: template
  sensors:
   dp_all_soc_delta:
    friendly_name: "ALL DP SOC Delta"
    unit_of_measurement: "SOC%"
    value_template: >- 
     {{ (states('sensor.dp1_soc_avg') | float - states('sensor.dp2_soc_avg') | float) | round(1) | abs }}
```
