### ISSUE TITLE
Entities are updates only when Ecoflow app is open

### ISSUE THREAD

**Issue by samfromlv** [tolwi/hassio-ecoflow-cloud#57]
I am using v0.8.9 with Delta2. No matter what I set in refresh rate in configuration, entities state is not refreshed automatically. Entities are refreshed automatically while I am using Ecoflow android application, otherwise the state stays the same for hours.

Any suggestions how to debug it?

**Comment by Tommi1977** [comment]
Same here with River 2 Pro since yesterday

**Comment by buffcode** [comment]
Reloading the integration forced an update, but the data won't be updated afterwards. Seems to be device-independent, Delta Pro here.

**Comment by vedranius** [comment]
same with my River 2 Max

**Comment by unze** [comment]
Same Here. River 2 Pro

**Comment by samfromlv** [comment]
I have researched this issue and it seems that the reason is in the Ecoflow API. The workaround for now is to reload integration and do not open the Ecoflow App after this (Settings > Integrations > EcoFlow-Cloud > Three dots > Reload).

I have created a second account, installed Ecoflow to another Android phone and shared my Delta 2 with a newly created account. The issue is reproducible using two phones. Open two Ecoflow apps on different devices, open the device dashboard, observe that metrics are updated on both devices, force close the application on the first device, and now app on the second device will stop receiving the updates. The only way to start getting updates on second device it is to force close the app and restart it.

I have checked integration debug logs, and there are no disconnects nor errors.
I have tried using different IP addresses on two devices, doesn't help.

As mentioned before, reloading integration does help and entities are updated until you open the Ecoflow app, or anyone who can access your device opens the app. I have contacted in-app support to report the issue.

**Comment by faken** [comment]
I've resolved this issue with a hass.io automation: 

```
alias: Restart EcoFlow Integration
description: ""
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: number.test_ac_charging_power
mode: single
```
